### ISSUE TITLE
Error with Dockerfile

### ISSUE THREAD

**Issue by ductridev** [Constellation-Labs/tessellation#311]
Dockerfile contains some errors. For example: export command, if-else condition, EOF. So I can't build L0 or L1. Thank you.

**Comment by marcinwadon** [comment]
@ductridev Dockerfile available in kubernetes directory is for exclusive use of k8s and cannot be used standalone. For creating a docker image, please use the sbt docker plugin that is available in the project.

**Comment by tbekas** [comment]
@ductridev What's your docker version? Probably you have an old docker version that doesn't support the heredoc.

**Comment by ductridev** [comment]
My docker version : Docker version 20.10.17, build 100c701
I have installed Kubernetes and building with sbt with command skaffold dev --trigger=manual.

**Comment by tbekas** [comment]
Do you get any errors when you run these two commands?
```
sbt core/assembly keytool/assembly
docker build -f kubernetes/l0.Dockerfile .
```

**Comment by ductridev** [comment]
![image](https://user-images.githubusercontent.com/49811496/175067164-486224c4-8135-48b7-87b4-e01558c0cf59.png)
error when run first command

**Comment by tbekas** [comment]
Try this instead
```
sbt "core/assembly;keytool/assembly"
```

**Comment by ductridev** [comment]
![image](https://user-images.githubusercontent.com/49811496/175186494-f027c933-e887-4192-933d-bdee14e71205.png)
Second-line with error from l0.Dockerfile which I have reported in this issue.

**Comment by ductridev** [comment]
I have fixed export error in Dockerfle by added RUN before export.

**Comment by ductridev** [comment]
It looks like an error between docker and heredocs. Because after RUN EOF, docker runs heredocs command as its command.

**Comment by ductridev** [comment]
Fixed by added DOCKER_TOOLKIT env variable with this command : `export DOCKER_BUILDKIT=1`
