### ISSUE TITLE
Requirement of l0 development

### ISSUE THREAD

**Issue by ductridev** [Constellation-Labs/tessellation#312]
Can you provide the minimum requirements of the project?

**Comment by tbekas** [comment]
Do you mean system requirements like cpu & memory?

**Comment by ductridev** [comment]
You are right.

**Comment by tbekas** [comment]
Depends on the cluster size. A single instance of L0 or L1 validator requires a minimum of 0.5 vCPU and 1GiB of memory to start and up to 2 vCPU and 4GiB to operate. If there are not enough system resources to operate, you may get OutOfMemory errors or a lack of responsiveness of an instance. The setup that's prepared to run with Skaffold starts 2 clusters, totaling to 5 instances so it may take up to 10 vCPU and 20 GiB of memory in total.

**Comment by ductridev** [comment]
Thank you. I ask this because when I run scaffold dev command, it return error related to not enough cpus to run it
