### ISSUE TITLE
Java InvalidPathException at kernel module.

### ISSUE THREAD

**Issue by ductridev** [Constellation-Labs/tessellation#336]
![image](https://user-images.githubusercontent.com/49811496/178507816-04fd20e4-9a81-4a5e-a539-d73acda4217f.png)

I'm trying to deploy at my Windows server but it shows this error while the older version does not exist.

My sbt version: 
![image](https://user-images.githubusercontent.com/49811496/178508499-b0ab0623-368d-4c44-a996-fe52bca5dc45.png)
My scaffold version: 
![image](https://user-images.githubusercontent.com/49811496/178508657-b5441155-2356-42b1-aca4-9fb0cff97594.png)

**Comment by ductridev** [comment]
I have tried both commands already but still same error.
```
sbt "core/assembly;keytool/assembly"
and
sbt core/assembly keytool/assembly
```

**Comment by marcinwadon** [comment]
Hey, our development environment is linux/mac, we have never tried running it on Windows.
the file contains ohm sign in the name of the object and also filename. that may be the issue
![image](https://user-images.githubusercontent.com/4959931/178512153-39d5a418-307e-4bdb-978e-4ca85ddb3d7d.png)

**Comment by ductridev** [comment]
@marcinwadon Oh, thank you for your reply! I will try again on my Linux server, because I see that project is using docker desktop so I think Windows is ok.

**Comment by ductridev** [comment]
Error with Windows encoding. Work fine on Linux!
