### ISSUE TITLE
Error with Dockerfile

### ISSUE THREAD

**Issue by ductridev** [Constellation-Labs/tessellation#338]
I got an error when trying to build only l0 with the command : 
`skaffold dev -p onlyL0`
![image](https://user-images.githubusercontent.com/49811496/178536480-350c3f80-265f-4a1a-945b-55aad09671b2.png)

My docker info:
![image](https://user-images.githubusercontent.com/49811496/178536932-36e5c3e5-2c1a-4dfa-9286-24732e186f9d.png)

**Comment by marcinwadon** [comment]
Hey, please take a look into `SETUP.md` file. You need to configure your k8s context (kube-context) in order to deploy images to, for example, your local cluster

**Comment by marcinwadon** [comment]
any kubernetes cluster

**Comment by ductridev** [comment]
Even I setup k8s successful, the error still there.
![image](https://user-images.githubusercontent.com/49811496/178543393-bc074e87-4582-418f-9c42-665590d09c65.png)

**Comment by marcinwadon** [comment]
You said you're not using AWS. Why you configured the k8s to use EKS then? You need to provide there either your local k8s context or create one on your cloud.

**Comment by ductridev** [comment]
Oh, I got it, will try

**Comment by ductridev** [comment]
Hi, I'm back. After installed k8s, error stills there!
![Screenshot 2022-07-13 171225](https://user-images.githubusercontent.com/49811496/178709808-83812e17-aaaa-48ec-97f3-ae39a9a66c30.png)

**Comment by tbekas** [comment]
You won't have an access to the image repository on AWS nor to the EKS cluster that's deployed there. We have instructions in `README.md` only for local kubernetes environments like `minikube` or `docker-desktop`. If you would like to deploy to GCP you need to handle issues on your own.
