### ISSUE TITLE
Streamline Contributing Instructions (e.g. use cli commands)

### ISSUE THREAD

**Issue by abebeos** [Constellation-Labs/tessellation#747]
### Status

Text instructions like 

```
Fork this repository.
Clone your fork of the repository.
```
https://github.com/Constellation-Labs/tessellation/blob/develop/CONTRIBUTING.md#how-to-contribute

### Expected

Create a fork via  https://github.com/Constellation-Labs/tessellation/fork

```
git clone https://github.com/<my-github>/tessellation/fork
*
```

Create a PR (follow instructions within PR template)

[...]

**Comment by AlexBrandes** [comment]
@abebeos I think your suggestion would be a small improvement over the current contribution instructions. We would be open to a PR with the changes if you'd like to contribute.
