### ISSUE TITLE
void

### ISSUE THREAD

**Issue by abebeos** [Constellation-Labs/tessellation#762]

**Comment by sdavidp** [comment]
@abebeos We don't develop on the Windows platform. If you want to test this change and let me know if it works I'll adjust the code.
Change references of
`getClass.getResource("/`
to
`Thread.currentThread().getContextClassLoader.getResource("`

**Comment by abebeos** [comment]
both `getResource` methods return the same URL object that leads to an exception.

I've solved this locally, see #763 (tested on Windows)
