### ISSUE TITLE
dagShared file not found

### ISSUE THREAD

**Issue by prateushsharma** [Constellation-Labs/tessellation#904]
in this docs:https://docs.constellationnetwork.io/metagraphs/guides/compile-tessellation
 while running:sbt "shared/publishM2;kernel/publishM2;sdk/publishM2;keytool/publishM2;dagShared/publishM2"

we are using dagShared file ,but its not found
[error] Expected ID character
[error] Not a valid command: dagShared
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: dagShared
[error] dagShared/publishM2
[error]          ^
prateush@prateush-Nitro-AN515-56:~/tessellation$

**Comment by Devushakya** [comment]
I am also facing the exact same problem.
Please help

**Comment by marcinwadon** [comment]
There is no `dagShared` module in the tessellation. Try `nodeShared` please

**Comment by AlexBrandes** [comment]
Thanks for pointing this out. We will take a look to update the docs.

Unless you are planning to contribute to Tessellation directly, it's strongly recommended that you don't try to build it manually. You should use Euclid SDK for metagraph development purposes which will build Tessellation automatically for you. 

Please follow this guide:
https://docs.constellationnetwork.io/sdk/guides/quick-start
